# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Colin Willson
tagline:          'Resume'
description:      'Noob blogger, technology lover, & more.'
url:              http://CWftw.me
baseurl:          /

author:
  name:           'Colin Willson'
  url:            https://twitter.com/cwftw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CWftw/cwftw.github.io

social:
  twitter:        https://twitter.com/cwftw
  google:         https://plus.google.com/+ColinWillson
